### ISSUE TITLE
Slow run of lssystem collector on SVC nodes

### ISSUE THREAD

**Issue by matejzero** [IBM/spectrum-virtualize-exporter#2]
Hello,

I'm trying out the latest commit of this exporter and `lssystem` collector is taking more than 20s to execute (average around 22s) while `lssystemstats` executes in 0,7s. 

This collector is slow only on SVC nodes (SV1 nodes with firmware 8.3.1.5). Collecting from Storwize 5020 (2078-224 with firmware 8.2.1.11) works as normally (under 1s response).

If I ssh onto the node and run lssystem, I get the response instantly. Calling lssystem via curl is also fast, so it must be something in the code I guess, but I'm not familiar with Go profiling.

**Comment by Charles1000Chen** [comment]
@matejzero The problem can be the restAPI issue on the specific firmware. I didn't reproduce the issue on node with firmware 8.5.0.10. Could you try upgrade to the firmware to 8.5.x and see if the issue is stil?

**Comment by matejzero** [comment]
We are running 8.3.1.9 at the moment and collection works like it's suppose to (collecting all metrics from 3 different systems is under 1 sec, which is great).

Since this is not an issue anymore, I'm closing this.

/close
